### ISSUE TITLE
prepare for release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/openni_wrapper#4]
So, currently this doesn't succeed to build on our integration server. See https://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-openni_wrapper/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/2/console

What needs to be done:
- [ ] email addresses corrected in `package.xml`
- [ ] all dependencies introduced in `package.xml`
- [ ] license checked and set (make sure it matches the OpenNI2 license!)
- [ ] probably be renamed to include the version
- [ ] some text in `README.md` explaining what this is useful for

**Comment by marc-hanheide** [comment]
I should add that this has been already added to the integration server in https://github.com/strands-project/rosdistro/commit/a30bb925b465e57e23ee75bf67ac778de92759a8 This created build job https://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-openni_wrapper/. So, no need to do that, when a new commit is pushed to this repo, a rebuild will be triggered. @RaresAmbrus you won't get any email notifications because your email is set to `rares@todo.todo` in the `package.xml` of the current version!

**Comment by RaresAmbrus** [comment]
@marc-hanheide I'm looking into this now, it seems like the license of OpenNI2 is "Apache License" - never heard of that one before, here's some info about it http://en.wikipedia.org/wiki/Apache_License. 
I'm not sure the openni-wrapper package should have the same one, since we're not modifying the OpenNI2 source code, just including and linking to it. I'll leave it as MIT for now, and correct the email address so I get notified about build errors.

**Comment by RaresAmbrus** [comment]
@marc-hanheide getting a weird jenkins error now:

```
/tmp/buildd/ros-hydro-openni-wrapper-0.0.2-0precise-20141104-2212/include/ColorCallback.h:6:36: fatal error: OpenNI2/Include/OpenNI.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/openni_wrapper_lib.dir/src/ColorCallback.cpp.o] Error 1
make[4]: Leaving directory `/tmp/buildd/ros-hydro-openni-wrapper-0.0.2-0precise-20141104-2212/obj-x86_64-linux-gnu'
make[3]: *** [CMakeFiles/openni_wrapper_lib.dir/all] Error 2
```

Seems like the submodule is not initialized properly for some reason; otherrwise this should work, it compiles fine on my machine.

**Comment by marc-hanheide** [comment]
Really strange... Workspace looks like this:
https://lcas.lincoln.ac.uk/jenkins/view/Releases/job/ros-hydro-openni-wrapper_binarydeb_precise_amd64/ws/work/ros-hydro-openni-wrapper-0.0.2/

**Comment by RaresAmbrus** [comment]
For some reason Jenkins doesn't let me log in with my github username & password so I can't take a look at the workspace. @marc-hanheide where is this error coming from ? Is this the `hydro-devel` branch of `openni_wrapper` ?

**Comment by RaresAmbrus** [comment]
I think the submodule is not included in the release version of this package because the `.gitmodules` file is outside the package. According to the git manual, the `.gitmodules` file has to be located in the top level directory of a git working tree.

Looking at `https://github.com/strands-project/openni_wrapper` I think the one way to fix this is to move everything inside `https://github.com/strands-project/openni_wrapper/tree/hydro-devel/openni_wrapper` one level up, i.e. `https://github.com/strands-project/openni_wrapper` so that the `.submodule` file is part of the package as well. 

Do you think this is ok @marc-hanheide ?

**Comment by marc-hanheide** [comment]
I actually think this is a very good plan!

**Comment by RaresAmbrus** [comment]
Cool, I'll do that then.

**Comment by RaresAmbrus** [comment]
Moved things around in https://github.com/strands-project/openni_wrapper/pull/10; Jenkins approved. @marc-hanheide can you please try releasing this again ?

**Comment by marc-hanheide** [comment]
sure

**Comment by marc-hanheide** [comment]
This is now working!
